### ISSUE TITLE
初始化数据失败

### ISSUE THREAD

**Issue by evenye** [smallmi/omms#1]
请教楼主, 我在执行python manage.py makemigrations 这个命令出错, 提示如下报错.请问是否需要特别配置变量呢? 

(venv) root@docker-1:~/omms# python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/root/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/root/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/omms/omms/settings.py", line 277
    BREADCRUMBS_AUTO_HOME: True
                         ^
SyntaxError: invalid syntax

**Comment by evenye** [comment]
BREADCRUMBS_AUTO_HOME: True
BREADCRUMBS_HOME_TITLE: u'Home' 请问这二个选项需要修改么?

**Comment by evenye** [comment]
将这二个变量修改为以下即可:
BREADCRUMBS_AUTO_HOME = True
BREADCRUMBS_HOME_TITLE = u'Home'
